name: attrici_2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.8=h166bdaf_0
  - arviz=0.15.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - binutils=2.39=hdd6e379_1
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_linux64_openblas
  - blosc=1.21.3=hafa529b_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.8.0=hf91038e_1
  - c-compiler=1.5.2=h0b41bf4_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cairo=1.16.0=h35add3b_1015
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - cftime=1.6.2=py310hde88566_1
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - cons=0.4.5=pyhd8ed1ab_0
  - contourpy=1.0.7=py310hdf3cbec_0
  - cryptography=40.0.2=py310h34c0648_0
  - curl=8.0.1=h588be90_0
  - cxx-compiler=1.5.2=hf52228f_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - etuples=0.3.8=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fastprogress=1.0.3=pyhd8ed1ab_0
  - filelock=3.12.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.4=py310h2372a71_0
  - freetype=2.12.1=hca18f0e_1
  - gcc=11.3.0=h02d0930_13
  - gcc_impl_linux-64=11.3.0=hab1b70f_19
  - gcc_linux-64=11.3.0=he6f903b_13
  - gettext=0.21.1=h27087fc_0
  - glib=2.76.2=hfc55251_0
  - glib-tools=2.76.2=hfc55251_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gxx=11.3.0=h02d0930_13
  - gxx_impl_linux-64=11.3.0=hab1b70f_19
  - gxx_linux-64=11.3.0=hc203a17_13
  - h5netcdf=1.1.0=pyhd8ed1ab_1
  - h5py=3.8.0=nompi_py310ha66b2ad_101
  - harfbuzz=7.3.0=hdb3a94d_0
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.0=nompi_hb72d44e_103
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=16.0.3=default_h83cc7fd_0
  - libclang13=16.0.3=default_hd781213_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.0.1=h588be90_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=h3358134_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-devel_linux-64=11.3.0=h210ce93_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.76.2=hebfc3b9_0
  - libgomp=12.2.0=h65d4601_19
  - libgpg-error=1.46=h620e276_0
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libllvm16=16.0.3=hbf9e925_1
  - libnetcdf=4.9.2=nompi_hdf9a29f_104
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hbcd7760_0
  - libsanitizer=11.3.0=h239ccf8_19
  - libsndfile=1.2.0=hb75c966_0
  - libsqlite=3.41.2=h2797004_1
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-devel_linux-64=11.3.0=h210ce93_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=253=h8c4010b_1
  - libtiff=4.5.0=ha587672_6
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.4=hfdac1af_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.3=h4dfa4b3_0
  - logical-unification=0.4.6=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - matplotlib=3.7.1=py310hff52083_0
  - matplotlib-base=3.7.1=py310he60537e_0
  - minikanren=1.0.3=pyhd8ed1ab_0
  - mkl=2022.2.1=h84fe81f_16997
  - mkl-service=2.4.0=py310h9263142_0
  - mpg123=1.31.3=hcb278e6_0
  - multipledispatch=0.6.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=hf1915f5_2
  - mysql-libs=8.0.32=hca2cd23_2
  - ncurses=6.3=h27087fc_1
  - netcdf4=1.6.3=nompi_py310h2d0b64f_102
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numexpr=2.7.3=py310hb5077e9_1
  - numpy=1.24.3=py310ha4c1d20_0
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.0=hd590300_3
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.1=py310h7cbd5c2_1
  - pcre2=10.40=hc3806b6_0
  - pillow=9.5.0=py310h065c6d2_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=16.1=h5195f5e_3
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pymc=5.3.0=hd8ed1ab_0
  - pymc-base=5.3.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310hab646b1_3
  - pyqt5-sip=12.11.0=py310heca2aa9_3
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.8.0=py310hde6a235_1
  - pytensor=2.11.1=py310heca2aa9_0
  - pytensor-base=2.11.1=py310heca2aa9_0
  - python=3.10.11=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - qt-main=5.15.8=haa3a1c2_11
  - readline=8.2=h8228510_1
  - requests=2.29.0=pyhd8ed1ab_0
  - scipy=1.10.1=py310ha4c1d20_3
  - setuptools=67.7.2=pyhd8ed1ab_0
  - sip=6.7.9=py310hc6cd4ac_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2021.9.0=hf52228f_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.2=py310h2372a71_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py310h5764c6d_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xarray=2023.4.2=pyhd8ed1ab_0
  - xarray-einstats=0.5.1=pyhd8ed1ab_0
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - func-timeout==4.3.5
prefix: /home/sitreu/.conda/envs/attrici_2
